### ISSUE TITLE
Hello, can't the position weight matrix be 0?

### ISSUE THREAD

**Issue by Jiahe-Sun** [saketkc/pyseqlogo#10]
counts = {'A' : [0,4,5,0], 'C': [2,3,5,0], 'T': [2,1,0,1], 'G': [0,2,1,2]}
fig, axarr = draw_logo(counts, data_type='counts', yaxis='probability')
fig.tight_layout()
plt.show()

Hello, can't the position weight matrix be 0? When I run a file containing 0 matrix, I get the following warning. What should I do ? ? ?
### warning is this
RuntimeWarning: divide by zero encountered in log2
  -pfm[b][l] * np.nan_to_num(np.log2(pfm[b][l])) for b in bases

**Comment by saketkc** [comment]
See #11
