### ISSUE TITLE
Unable to draw all seqlogo

### ISSUE THREAD

**Issue by Jiahe-Sun** [saketkc/pyseqlogo#11]
When I draw the diagram, I can’t draw all of the sequence, only the first four letters can be displayed

counts = {'A': [1, 10, 17, 13, 3, 7, 0, 27, 27, 27, 0, 27, 16, 7], 'G': [10, 7, 4, 5, 11, 0, 0, 0, 0, 0, 25, 0, 4, 4], 'C': [7, 5, 2, 5, 8, 20, 0, 0, 0, 0, 0, 0, 2, 6], 'T': [9, 5, 4, 5, 0, 0, 27, 0, 0, 0, 2, 0, 5, 10]}
fig, axarr = draw_logo(counts, data_type='counts', yaxis='probability')
fig.tight_layout()

##warning
UserWarning: Tight layout not applied. The left and right margins cannot be made large enough to accommodate all axes decorations. 
  fig.tight_layout()

**Comment by saketkc** [comment]
Please use [dmslogo](https://jbloomlab.github.io/dmslogo/) which uses some of the functionality from pyseqlogo and is well maintained.

**Comment by Jiahe-Sun** [comment]
Hello, the input format of pyseqlogo is more suitable for our needs, so I am very happy to use it, but it cannot display all the seqlogo, only the first four are shown, and I hope very much for your help




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "saketkc/pyseqlogo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月29日(星期一) 晚上7:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [saketkc/pyseqlogo] Unable to draw all seqlogo (Issue #11)





 
Please use dmslogo which uses some of the functionality from pyseqlogo and is well maintained.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
